### ISSUE TITLE
Consider omitting req.headers.host from the hash

### ISSUE THREAD

**Issue by mwolson** [flickr/incoming-message-hash#2]
I noticed that if we start yakbak on a random port and tie it to an express route, the "host" header includes that port number, which makes the hash of a request never match an existing tape. A few possible solutions:
1. Omit req.headers.host from the hash
2. Delete or normalize req.headers.host in yakbak
3. Update yakbak instructions to mention the need to normalize req.headers.host manually when starting on a random port

Any preferences?

**Comment by jeremyruppel** [comment]
So far, we've found #3 to be the easiest route for us. Since yakbak is a proxy anyways, it seems fine to manually set the Host header in our tests. I'd hesitate to have incoming-message-hash omit the host header when determining the hash (SRP after all), but I'd be open to normalizing it in yakbak. 

Is setting the Host header in your tests an acceptable short term solution? 

Summoning @alex-seville @jimwhimpey @flrent in case they have any thoughts here.

**Comment by mwolson** [comment]
For now I just added a normalizing express middleware to the test/mocking server running yakbak, which changes req.headers.host to just "localhost". That solved it for me, but took a bit of digging to find the original problem.

**Comment by jeremyruppel** [comment]
We use a similar approach internally, but we just shipped yakbak@2.6.0 which allows you to provide your own IncomingRequest hash function.
